services:
  app:
    build: .
    ports:
      - "9292:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ciberseguridad
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin123!
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - 9191:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
      UPLOAD_LIMIT: 100M

volumes:
  db_data:
